from xml.etree.ElementTree import Element as Element, ElementTree as ElementTree
from collections.abc import Iterator, Sequence
from os import PathLike

def parse(source: str | bytes | PathLike[str], forbid_dtd: bool = ..., forbid_entities: bool = ..., forbid_external: bool = ...) -> ElementTree[Element]: ...
def fromstring(text: str | bytes, forbid_dtd: bool = ..., forbid_entities: bool = ..., forbid_external: bool = ...) -> Element: ...
def iterparse(source: str | bytes, events: Sequence[str] | None = ..., forbid_dtd: bool = ..., forbid_entities: bool = ..., forbid_external: bool = ...) -> Iterator[tuple[str, Element]]: ...
def tostring(element: Element, encoding: str = ..., method: str = ...) -> str | bytes: ...
